<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Suite2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d117a71b-8cfe-4dc0-9552-2acd4c63c509</testSuiteGuid>
   <testCaseLink>
      <guid>9b7ebbeb-5a73-461b-9f03-3537f16977ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/FilesLinkTestcase</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>15d311ee-40af-4cc9-8ffd-d2d4e3220129</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>6</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>15d311ee-40af-4cc9-8ffd-d2d4e3220129</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8bcef31e-0732-4fba-bd3b-e4bce98ba19c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15d311ee-40af-4cc9-8ffd-d2d4e3220129</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a63c7d7f-f42d-46cf-aa3c-404ff99616fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15d311ee-40af-4cc9-8ffd-d2d4e3220129</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>877994f5-2889-4f28-9a03-5b6c724d598a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15d311ee-40af-4cc9-8ffd-d2d4e3220129</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>7779819d-719f-416d-9ac2-1ce4255afe2c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
