<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shell Script App</name>
   <tag></tag>
   <elementGuidId>288f08d8-108b-4d02-826b-dc7e7dcbe3be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ShellScript']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.job-monitor-application-tile-info > span.show-text-ellipsis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfe6d625-28a9-451a-a3e5-2a4b295486f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show-text-ellipsis</value>
      <webElementGuid>d8a2fe39-f88d-4883-af9b-95a7b5d0430c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Shell Script</value>
      <webElementGuid>470a257e-a202-415f-a567-1af65e7fa82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shell Script</value>
      <webElementGuid>4182fba6-124c-49f8-86ad-5f67c8e96d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-monitor-application-tile-container&quot;)/div[@id=&quot;ShellScript&quot;]/div[@class=&quot;job-monitor-application-tile-content&quot;]/div[@class=&quot;job-monitor-application-tile-info&quot;]/span[@class=&quot;show-text-ellipsis&quot;]</value>
      <webElementGuid>353dc807-c087-454b-ac10-084c9e4806bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ShellScript']/div/div[2]/span</value>
      <webElementGuid>0244409d-0179-4419-8043-2a0693445d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Job Using:'])[1]/following::span[1]</value>
      <webElementGuid>d7fbc96c-d906-47a3-a135-d34022a90d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Array Jobs'])[1]/following::span[3]</value>
      <webElementGuid>92801f08-815c-4866-9bd9-b1a5da88b71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Launch Default'])[1]/preceding::span[2]</value>
      <webElementGuid>7be3d64d-0d0a-4d00-81d0-e97319b6e1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Launch Custom'])[1]/preceding::span[3]</value>
      <webElementGuid>0cad3c14-8a9f-47d5-b588-01cc4e81d5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/span</value>
      <webElementGuid>2f9b87b8-a7ad-4c0b-a6de-c25a3018e029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Shell Script' and (text() = 'Shell Script' or . = 'Shell Script')]</value>
      <webElementGuid>adbb6e1e-68e0-45e0-9066-69acb6daecab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
