<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tile_view_button</name>
   <tag></tag>
   <elementGuidId>46703efc-1471-4416-aea4-1960bdd3d42e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_switcher']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.unity_tile_view.unity-font-size.list-btn.focus_enable_class</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3cc25967-e118-4777-b436-85d544f6c376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unity_tile_view unity-font-size list-btn focus_enable_class</value>
      <webElementGuid>05535f99-c818-4bad-9d5b-7c4f6c4b5603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b13bfff2-b9fa-4d5f-be9d-04d7684782d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tile View</value>
      <webElementGuid>bd98f064-0c8a-4b1e-855b-3b6ff1d7f2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_switcher&quot;)/span[1]/span[@class=&quot;unity_tile_view unity-font-size list-btn focus_enable_class&quot;]</value>
      <webElementGuid>713351f9-6d3a-437b-93e7-a716a333ff91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_switcher']/span/span</value>
      <webElementGuid>98028e7a-0520-4b68-9293-8a34747d2f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span</value>
      <webElementGuid>60b5114f-ee87-4a51-ad43-10f226325c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Tile View']</value>
      <webElementGuid>3d503a68-c6f7-4b22-a842-29a27086f669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
